### ISSUE TITLE
just wondering

### ISSUE THREAD

**Issue by muhilham** [jonschlinkert/is-number#10]
how come this package has 28 million download on NPM, but only has 28 star and seven forks with 0 issue ? hope its not the next left-pad :)))

**Comment by jonschlinkert** [comment]
> how come this package has 28 million download on NPM but only has 28 star 

People tend to star projects that are "interesting", not boring libs. If you want more information about why downloads are a much better indicator of quality and reliability than stars, here is an [excerpt from a paper I'm writing about [code quality and scoring FOSS projects](https://gist.github.com/jonschlinkert/1e6477b490e0bc11ae197a2cf5d277f7). 

> hope its not the next left-pad :)))

Deleting left-pad (and all of his other libraries) was an absurdly childish and economically detrimental act of selfishness. We can improve code over time, but nothing will ever prevent humans from making bad decisions. I can only give you my word that I won't do what he did (and it sucks that you feel the need to be concerned because of what he did).

Since you're concerned, last month my packages were downloaded 852,414,630 times on NPM. `is-number` represents 3.39% of those downloads, and 95 libraries I published are downloaded more than 1m times a month.  I believe `left-pad` was downloaded like 1m times a month, which represented something 90% of its author's downloads if I recall correctly.

Also, NPM no longer allows past versions of any package to be arbitrarily deleted. (you can contact them to do it, but they won't without good reason, specifically to prevent publishers from making bad decisions like the author of left-pad).

**Comment by jonschlinkert** [comment]
> seven forks with 0 issue

I forgot to address this. The vast majority of libraries that get lots of forks and issues fall into one of the following categories:

- projects that change a lot
- projects that are broken

This project fits neither of those categories. Issues are often an indication of **community health** but are rarely an indication of code health. Micro-libraries do not have communities.
