### ISSUE TITLE
A separated package to check if an object is a number? Really??

### ISSUE THREAD

**Issue by isqad** [jonschlinkert/is-number#37]
Just for simple function you made the repo for it?
![image](https://github.com/jonschlinkert/is-number/assets/751651/958b7ad1-3d79-4145-8ada-e0b7ba9205f3)

**Comment by Digital-512** [comment]
Yes, because unfortunately we have forgotten how to program...

[Have We Forgotten How To Program?? | Prime Reacts (Youtube)](https://www.youtube.com/watch?v=NmHUjxKpD90)
[NPM & left-pad: Have We Forgotten How To Program?](https://www.davidhaney.io/npm-left-pad-have-we-forgotten-how-to-program/)

Packages like this are completely unnecessary and simply creates a dependency hell.

**Comment by ghost** [comment]
**EDIT**: you know what, I won't pile on. You seem to be doing well for yourself, probably much better than the folks complaining here. You seem to enjoy this and are happy to share your projects. I assume this one was one of your first open source projects and while I am tired of these little libraries, I am happy you actually shipped things, something I have a hard time doing.

Congrats on your OSS success, man. Sorry for the negativity.
